name: Events and Workflows
on:
    pull_request:
        types:
            - opened
            - closed
    workflow_dispatch:
jobs:
    event:
        runs-on: ubuntu-latest
        steps:
            - name: Event data
              run: echo "${{ toJson(github.event) }}"
            - name: Get Code
              run: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
            - name: Test Code
              run: npm run test
            - name: Build Code
              run: npm run build